# Model arguments
model_name_or_path: 'CMR-R/TS/Qwen2.5-7B-TS3'
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: TS3_train.json
system_prompt: "你是一名放射科医生，能够根据患者的心脏功能参数和磁共振影像描述是否存在异常去判断患者患有的心脏疾病，提供推理充分、细节详实的回答。推理分析的路径为一、心功能参数；二、影像学表现；三、综合诊断意见；最后在所有的疾病类别中选择一个放在<answer></answer>中：[心肌梗死，右心室异常，心肌致密化不全，肥厚型心肌病，淀粉样病变，扩张型心肌病，心肌炎，正常]"

# Swanlab 训练流程记录参数
swanlab: true # 是否开启 Swanlab 
workspace: xx
project: Cmr-R1-TS
experiment_name: qwen2.5-7B-TS3

# GRPO trainer config
beta: 0.001
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.5
vllm_enable_prefix_caching: False
do_eval: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-7B-Open-R1-GRPO
hub_strategy: every_save
learning_rate: 3.0e-07
# log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 8192
max_completion_length: 8192
max_steps: -1
num_generations: 6
num_train_epochs: 3
output_dir: TS/Qwen2.5-7B-TS4
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 4
push_to_hub: false
report_to:
# - wandb
reward_funcs:
- answer
- format

reward_weights:
- 1.0
- 1.0

save_strategy: "steps"
save_steps: 100 # 每隔多少步保存一次
# save_strategy: "epoch"
# save_total_limit: 1
seed: 42
warmup_ratio: 0.03
